version: "3.8"

###########################
#       SERVIÇOS          #
###########################
services:
  # ---------- CONFIG‑SERVERS ----------
  cfg1:
    image: mongo:7.0
    container_name: cfg1
    command: ["mongod","--configsvr","--replSet","cfgRS","--port","27019"]
    volumes: [ "cfg1_data:/data/db" ]
    networks: [ mongo-cluster ]

  cfg2:
    image: mongo:7.0
    container_name: cfg2
    command: ["mongod","--configsvr","--replSet","cfgRS","--port","27019"]
    volumes: [ "cfg2_data:/data/db" ]
    networks: [ mongo-cluster ]

  cfg3:
    image: mongo:7.0
    container_name: cfg3
    command: ["mongod","--configsvr","--replSet","cfgRS","--port","27019"]
    volumes: [ "cfg3_data:/data/db" ]
    networks: [ mongo-cluster ]

  # ------------- SHARDS ---------------
  shard1:
    image: mongo:7.0
    container_name: shard1
    command: ["mongod","--shardsvr","--replSet","shard1RS","--port","27018"]
    volumes: [ "shard1_data:/data/db" ]
    networks: [ mongo-cluster ]

  shard2:
    image: mongo:7.0
    container_name: shard2
    command: ["mongod","--shardsvr","--replSet","shard2RS","--port","27018"]
    volumes: [ "shard2_data:/data/db" ]
    networks: [ mongo-cluster ]

  shard3:
    image: mongo:7.0
    container_name: shard3
    command: ["mongod","--shardsvr","--replSet","shard3RS","--port","27018"]
    volumes: [ "shard3_data:/data/db" ]
    networks: [ mongo-cluster ]

  # ------------- ROUTER ---------------
  mongos:
    image: mongo:7.0
    container_name: mongos
    depends_on: [ cfg1, cfg2, cfg3, shard1, shard2, shard3 ]
    command: ["mongos","--configdb","cfgRS/cfg1:27019,cfg2:27019,cfg3:27019","--bind_ip_all","--port","27017"]
    ports:
      - "27017:27017"      # cluster sharded exposto
    networks: [ mongo-cluster ]

  # ---------- SINGLE INSTANCE ---------
  mongo_single:
    image: mongo:7.0
    container_name: mongo_single
    # MongoDB standalone simples para comparação
    command: ["mongod","--port","27017"]
    ports:
      - "27027:27017"      # evita conflito com o mongos
    volumes: [ "single_data:/data/db" ]
    networks: [ mongo-cluster ]

###########################
#        VOLUMES          #
###########################
volumes:
  cfg1_data: {}
  cfg2_data: {}
  cfg3_data: {}
  shard1_data: {}
  shard2_data: {}
  shard3_data: {}
  single_data: {}

###########################
#        NETWORKS         #
###########################
networks:
  mongo-cluster:
    driver: bridge

